### ISSUE TITLE
Default images do not have attribution or usage permissions listed

### ISSUE THREAD

**Issue by lordastley** [getgrav/grav-theme-saturn#1]
The header image (img/head-bg.jpg) appears to be artwork from <a href="http://www.firewatchgame.com/">Firewatch</a>, and is not presented with attribution or usage permissions.

The example in-post image (img/post-img.jpg) appears to be artwork from <a href="https://www.threadless.com/product/5004/magic_bacon_ride">George Otsubo</a> and is not presented with attribution or usage permissions.

**Comment by rhukster** [comment]
We will get this sorted asap.  

We did a direct port of a free PSD/HTML template and didn't pay close enough attention to the origins and attribution requirements of the images: https://dribbble.com/shots/1920749-Free-PSD-HTML-Template-Saturn

**Comment by hexplor** [comment]
I apologize for the whole situation. For me it was pretty obvious that theme create had proper permissions to use these images. I didn't check the comments where it clearly states that he didn't receive reply. Images replaced.
