### ISSUE TITLE
Broken footnotes

### ISSUE THREAD

**Issue by sly-fox-git** [getgrav/grav-theme-saturn#2]
I can't seem to figure out what is causing the problem, but any footnote created in the post will be indented to the right.

First footnote is always indented but all subsequent footnotes are properly aligned.

**Comment by hexplor** [comment]
Can you show me example post here ? or can you attach example markdown code in this issue ? Thanks

**Comment by sly-fox-git** [comment]
Most world-class memory performers use mnemonics rather than have any extraordinary brain power. Neuroimaging studies of exceptional memorizers found no differences in brain anatomy between world-class memory performers and people with average memories [^Gluck].

This means that almost anyone could attain a "world-class memory" by practicing the right techniques, such as a mnemonic system [^Mnemonic]. Unfortunately, there is no scientific evidence that world-class memory masters are any better than the rest of us at memory challenges in the real world, such as remembering where we parked our car or when someone's birthday is..

[^Gluck]: Gluck, M. A., Mercado, E., & Myers, C. E. (2008). _Learning and memory: from brain to behavior_. New York: Worth Publishers.
[^Mnemonic]: [Mnemonic major system.](http://en.wikipedia.org/wiki/Mnemonic_major_system)

**Comment by hexplor** [comment]
It's fixed in saturn "develop" branch. Please check and tell me if it's fine. Thanks :)

**Comment by sly-fox-git** [comment]
Hi Karol,

Thank yo ufo fixing the footnotes but.

Can you please add an option for a side bar box? You have a good and simple theme that I would like to use. However, I think that it is missing a right side bar box where one could add Google Site search and/or Newsletter subscription (Name and Email).

Does your blog component support RSS?

Have you thought about adding some kind of simple social media icons bar?

**Comment by hexplor** [comment]
Hi,
I'm not author of the theme. I just converted it to grav. Original theme doesn't contain sidebar so it needs to be coded, tested etc.. If you know HTMl, you can try adding that by yourself. Otherwise you can ask someone to code that for you. Right now we don't have plans to extend Saturn with sidebar.
